name: CI

on: push

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: List all stuffs
        run: ls -l

      - name: download robots.txt
        run: curl -O https://www.digitalocean.com/robots.txt

      - name: List stuffs again
        run: ls -a

      - name: Print the text file
        run: cat robots.txt