name: CI

on: push

jobs:
  myjob:
	  runs-on: ubuntu-latest
		steps:
      - name: step1
	      run: curl -0 https://www.digitalocean.com/robots.txt 

      - name: step2
	      run: ls -l
	    
			- name: step3
	      run: cat robots.txt 